-- used "Generate DDL..." on ResourceEntity.java
CREATE TABLE resources_binary
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource OID                                     NOT NULL,
    CONSTRAINT pk_resources_binary PRIMARY KEY (id)
);